# See list of defaults here: https://docs.rubocop.org/rubocop/index.html

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bin/**/*

# ------------------------------------------------------------------------------
# DEPARTMENT LAYOUT
# ------------------------------------------------------------------------------

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent # default: special_inside_parentheses

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent # default: special_inside_parentheses

Layout/LineLength:
  Max: 100 # default: 120

# ------------------------------------------------------------------------------
# DEPARTMENT METRICS
# ------------------------------------------------------------------------------

Metrics/BlockLength:
  Exclude:
  - spec/**/*

# ------------------------------------------------------------------------------
# DEPARTMENT STYLE
# ------------------------------------------------------------------------------

Style/Documentation:
  Enabled: false # default: true
