# See list of defaults here: https://docs.rubocop.org/rubocop/index.html

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bin/**/*

Layout/LineLength:
  Max: 100 # default: 120

Metrics/BlockLength:
  Exclude:
  - spec/**/*

Style/Documentation:
  Enabled: false # default: true
