name: Ruby

on:
  push:
    branches:
      - master
      - develop

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.6
          - 2.7
          - 3.0
          - 3.1

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # FIXME: Rubocop fails when using `bundler-cache: true`
          # bundler-cache: true

      - run: bundle install
      - run: bundle exec rake
