name: Release

on:
  release:
    types: [published]

jobs:
  main:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build the gem
        id: build
        run: |
          gem build enginn.gemspec
          echo "::set-output name=package_name::$(ls *.gem)"

      - name: Push to RubyGems
        run: |
          curl --fail --data-binary @${{ steps.build.outputs.package_name }} \
              -H 'Authorization:${{ secrets.RUBYGEMS_API_KEY }}' \
              -H 'Content-Type: application/octet-stream' \
              https://rubygems.org/api/v1/gems
