name: Release

on:
  release:
    types: [published]

jobs:
  main:
    name: Build & Push
    runs-on: ubuntu-latest

    env:
      GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Extract version number
        id: extract_version
        run: |
          echo "::set-output name=version::$(ruby -e "load 'lib/enginn/version.rb'; puts Enginn::VERSION")"

      - name: Construct package name
        id: package_name
        run: echo "::set-output name=name::enginn-${{ steps.extract_version.outputs.version }}.gem"

      - name: Build the gem
        run: |
          mkdir pkg
          gem build enginn.gemspec --output pkg/${{ steps.package_name.outputs.name }}

      - name: Push to RubyGems
        run: gem push -V pkg/${{ steps.package_name.outputs.name }}
